ministryofjustice/money-to-prisoners-common

templates/mtp_base.html

because:
1. The minified stylesheets (generated using clean-css) break the style on IE8
2. They only give a 2% gain in file size
Until we investigate a new minified that works on IE8 or we (wait for a) fix in clean-css,
we choose just to remove it. [Updates: #110145316]

Remove using the minified stylesheets

---

assets/scss/elements/_checkbox.scss

so that it's easier for users to tick the checkbox, but keep the
tickbox the same size

Increase the size of the checkbox clickable area

---

templates/includes/message_box.html
templates/mtp_base.html

so that it can be used anywhere and not just at the top above the home link
[updates #110406604]

Change the message box markup to a partial

---

Makefile

- create virtualenv in the build task
- make sure build task is run in watch and serve tasks
- rename update_venv to virtual_env as it is a target not an action

Make sure venv always exists when running tasks

---

Makefile

as this messes up the check for an open port

Prevent `nc` from outputting any text in verbose mode

---

Makefile

so that docker file can be built with non-dev dependencies

Allow make to specify the python requirements on the command line

---

Makefile

because client apps do not have databases and the management command fails when none are available

Remove DB migration prerequisite in uWSGI target

---

templates/forms/generic.html

Make the errors at the top of the form more readable.

Generic form error styling

---

Makefile

Silence python warnings if verbosity is set to zero

---

Makefile
package.json

c.f. [send-money#46](https://github.com/ministryofjustice/money-to-prisoners-send-money/pull/46)

Ensure selenium standalone web drivers are installed when running tests

---

assets/javascripts/modules/help-popup.js

Because we need the attribute to be correct in case JS is absent,
we will set it to open in the markup, and initally close it with JS,
just like we set its initial visibility to hidden

Set initial aria value to not-expanded

---

assets/javascripts/modules/help-popup.js

This is because the markup of the component will contain an a inside an h3
so that we can tab into the control

Handle reveal/hide controls if target is inside an h3

---

assets/scss/elements/_help-popup.scss

1. Remove the styles already provided by GOVUK
2. Keep the title links the same colour even if 'visited'

Improve markup and style of help boxes

---

assets/scss/elements/_forms.scss
package.json

(which cannot be wrapped in an anchor since there's nowhere to link to)

Add error message styling to non-field errors in summary

---

mtp_common/templates/mtp_common/auth/password_change_done.html

depends on [moj-auth#25](https://github.com/ministryofjustice/django-moj-auth/pull/25)

Allow apps to specify where "return home" links to from change password confirmations

---

mtp_common/__init__.py
mtp_common/assets/scss/_base.scss
mtp_common/forms/__init__.py
mtp_common/templates/mtp_common/forms/error-summary.html
mtp_common/templates/mtp_common/forms/field-errors.html
tests/test_error_summary.py

visually; they're still there for screen readers

Remove more full stops at the end of error messages

---

mtp_common/templates/mtp_common/email_base.html

- sans-serif As recommended in https://designnotes.blog.gov.uk/2014/09/04/the-design-of-government-emails/
- also remove unneccessary classes and add extra font-family in table for outlook 2003

Make HTML email text sans-serif and add service title in banner

---

mtp_common/assets/scss/_mtp.scss

the tabindex attribute set on the main element causes the focus to be visible
on some browsers. This rule (oddly not present in govuk_template) hides it

Remove the outline when the main content of the page is in focus

---

mtp_common/assets/scss/elements/_pagination.scss

$is-print doesn't work anymore or left over from mojular version

Fix pagination description in print form

---

mtp_common/templates/mtp_common/mtp_base.html

So that updated style sheets reload when a new version is deployed.

Append build version as query string to stylesheets and javascript files

---

mtp_common/context_processors.py
mtp_common/templates/mtp_common/mtp_base.html

as all client apps now use url-based locale switching

Make proposition header link to current language root

---

mtp_common/templates/mtp_common/sentry-js.html

Will now only create sentry errors for exceptions in our
javascript bundle.

Add URL whitelist to sentry JS error reporting

---

mtp_common/templates/mtp_common/build_tasks/package.json

… with the aim of logically separating test and build dependencies (however both need to be installed in docker images in order to fully build)

Remove node dependencies that are not directly used and split into dev and non-dev

---

mtp_common/dates.py
setup.py
tests/test_dates.py

Originally part of mtp-bank-admin, WorkdayChecker is a utility
for checking the next and previosu workdays for a given date
based on the gov.uk bank holiday web service.

Add WorkdayChecker to mtp-common

---

mtp_common/user_admin/views.py
tests/test_user_admin_views.py

rather than calling an API (whose response is changing)

Fix user admin tests’ mocked login and get prison count from user data

---

mtp_common/templates/mtp_common/user_admin/user-description.html
mtp_common/user_admin/forms.py

When a user edits themselves the fields for permissions are not
displayed. However, when they attempt to save any changes that they
make to themselves, they receive an error due to the permissions info
being absent from the form.

Fix error due to lack of permissions data when editing self

---

mtp_common/assets-src/javascripts/modules/print.js

If printing by clicking a specific link, elements specified by the
selector in the links data-do-not-print attribute will be hidden
from that print out only.

Allow for hiding certain elements when using a print link

---

mtp_common/assets-src/stylesheets/_print-basic.scss

so links do not show up as such when printed when the URL is not useful

Allow URLs to be hidden in print version

---

mtp_common/stack.py
setup.py

This can be used for jobs which should only run on one instance in
the auto-scaling group.

Add method for returning whether an instance is the first in ASG

---

mtp_common/test_utils/functional_tests.py

This to load different test data sets during functional testing.

Allow for the use of alternative commands when resetting test data

---

mtp_common/auth/forms.py
mtp_common/auth/views.py
mtp_common/locale/cy/LC_MESSAGES/django.po
mtp_common/locale/en_GB/LC_MESSAGES/django.po
mtp_common/templates/mtp_common/auth/password_change_with_code.html
mtp_common/templates/mtp_common/auth/reset-password-done.html
tests/test_auth_forms.py

This means that only the actual owner of the account can change their
password, and that they never have to enter an annoying random
password.

Change password reset to email a link rather than a new password

---

mtp_common/api.py
mtp_common/auth/api_client.py
mtp_common/auth/exceptions.py
mtp_common/auth/forms.py
mtp_common/user_admin/forms.py
mtp_common/user_admin/views.py
tests/test_api_client.py
tests/test_auth_forms.py
tests/test_auth_views.py
tests/test_user_admin_views.py

This allows one to use the session object to make requests directly
rather than going via the slumber wrapper all the time.
The ```MoJOAuth2Session``` replicates some slumber functionality, such as auto-raising for error HTTP statuses and holding a base URL so the caller only needs to specify the path. In contrast to slumber it does return the actual response object though, so need to call ```.json()``` to get the contents.

Add support for retrieving a bare Requests session object from auth module

---

mtp_common/user_admin/forms.py

As the user creation process now uses requests rather than
slumber to call the api, need to use the appropriate exception
type.

Change exception type from slumber to requests on user creation

---

mtp_common/api.py
mtp_common/templatetags/mtp_common.py
tests/test_notifications.py

as they're not user/request specific currently and this would add up to 2 api requests per page view

Add 5min caching to notifications

---

mtp_common/tasks.py

Still log as an exception otherwise

Log only a warning when mailgun error is for an invalid address

---

mtp_common/bank_accounts.py
tests/test_bank_accounts.py

These are for checking if roll numbers are required, if provided
roll numbers are valid or if an account is a correspondence account
(i.e. not a real account but used by a third party financial
services provider e.g. Metro bank etc)

Add bank account checks to common

---

mtp_common/templates/mtp_common/sentry-js.html
setup.py

as sentry is noting that we use outdated versions

Update Raven javascript and python libraries

---

.travis.yml
mtp_common/test_utils/functional_tests.py

The `tearDownClass` method of `LiveServerTestCase` tries to clean
up the live server thread, which is not running if we are testing
against a remote application.

Fix tear down of live server test case when testing remotely

---

mtp_common/tasks.py

This is necessary for emails sent by the API because the API is
unreachable from the public internet.

Allow an application to set an alternative static url for email assets

---

mtp_common/assets-src/stylesheets/internal/_notifications.scss

so that the focus outline does not cut the message box in two

Improve notifications appearance

---

mtp_common/assets-src/javascripts/modules/autocomplete-select.js

So that e.g. 'jo ber' will match 'joseph bercow'

Make autocomplete selection menu work with multiple words

---

mtp_common/assets-src/javascripts/modules/autocomplete-select.js

If an event category is defined on the select then will fire a GA
event with the the entered text and the chosen value.

Add analytics to autocomplete select

---

mtp_common/assets-src/javascripts/modules/autocomplete-select.js
mtp_common/assets-src/stylesheets/elements/_autocomplete.scss

This is to avoid other page elements being pushed down/around by the
drop down list.

Make autocomplete suggestion list overlay other page elements

---

mtp_common/templates/mtp_common/includes/page-list.html
mtp_common/templatetags/mtp_common.py

It is now possible to specify the pagination query parameter and
add a hash-bookmark to the url. These were added to support having
multiple paginated lists on one page.

Add additional configuration options to pagination template tag

---

mtp_common/templates/mtp_common/email_base.html

Internal emails should have the HMPPS header rather than the
GOV.UK header in emails sent to citizens.

Add alternative email logo for internal emails

---

mtp_common/api.py
mtp_common/auth/api_client.py
mtp_common/auth/views.py
mtp_common/build_tasks/executor.py
mtp_common/forms/fields.py
mtp_common/templatetags/mtp_common.py
setup.py
tests/test_notifications.py
tests/test_templatetags.py

This adds:
- `flake8-bugbear` to catch likely bugs and design problems
- `flake8-quotes` to make the use of quotes consistent
- `flake8-blind-except` to catch blind, catch-all except: statements
- `flake8-debugger` to catch pdb;idbp imports and set traces

Add extra flake8 rules

---

mtp_common/assets-src/javascripts/modules/tabbed-panel.js
mtp_common/assets-src/stylesheets/elements/_tabbed-panel.scss
mtp_common/templates/mtp_common/includes/tabbed-panel.html
mtp_common/templatetags/mtp_common.py

This:
- adds the ability to disable the collapse functionality so that clicking on the same tab twice doesn't do anything. To do this, you can pass `collapsable=False` (default=True).
- adds support for a new optional tabbedpanel param `css_class` which is added to the container div when specified
- adds support for a new style similar to the one in the GOV.UK Design System by using the css_class `govuk-grey`
Example:
```
{% tabbedpanel cookie_name='<cookie-name>' collapsable=False tab_label='<label>' css_class='govuk-grey' %}
{% paneltab name='<tab-name>' title='<title>' %}
...
{% endpaneltab %}
...
{% endtabbedpanel %}
```

Add support for new style when using tabbedpanel

---

mtp_common/analytics.py
mtp_common/templates/mtp_common/mtp_base.html
tests/test_analytics.py

This allows GA campaign settings to be sent through.

Add support for GA campaigns

---

mtp_common/assets-src/javascripts/modules/analytics.js

This adds a new method `rawSend` to the Analytics js library that doesn't modify the arguments when sending data to ga.

Add non-magic GA send method

---

mtp_common/cp_migration/constants.py
mtp_common/cp_migration/middleware.py
mtp_common/cp_migration/views.py
mtp_common/templates/mtp_common/cp_migration/maintenance.html
mtp_common/templates/mtp_common/cp_migration/we-have-moved.html
tests/test_cp_migration.py

This adds a new middleware that overrides the default request handlers and returns a maintenance page if `settings.CLOUD_PLATFORM_MIGRATION_MODE = 'maintenance'` or a page
saying that we have moved to a different domain if `settings.CLOUD_PLATFORM_MIGRATION_MODE = 'moved'`.
The template for the 'we have moved' mode, automatically redirects to the new url unless the browser is IE8.
The refresh meta is not really recommended by W3C but none of the alternatives are better: redirect in js (with the same issues) or don't redirect and ask users to click on the link instead.
The pages have not been designed yet.
At the moment they look like the ones below:
**Maintenance mode**
**We have moved mode NOT IE8**
**We have moved mode IE8**

Add support logic for the Cloud Platform migration

---

mtp_common/assets-src/stylesheets/internal/_notifications.scss

This makes sure the h1 in notification boxes has zero margin now that the public-facing service is using this feature as well.

Reset margin of h1 in notification boxes

---

build_tasks.py
mtp_common/auth/__init__.py
mtp_common/nomis.py
mtp_common/test_utils/__init__.py
tests/test_nomis.py

This:
- adds the concept of NOMIS connectors so that we can have the old legacy and the new Elite2 one at the same time
- introduces a few handy functions like request_retry to automatically retrying a call
Re. NOMIS Elite2:
- it caches the token so that it doesn't have to be obtained at every request
- if an API call returns 401, it deletes the cached token and retry again just to make sure the token wasn't the cause
- the old logic of getting the legacy NOMIS token from the API if one can't be found in settings is gone as we're currently not using it and it's not going to be used with the new logic.

Nomis Elite2 API

---

mtp_common/stack.py
setup.py
tests/test_stack.py

this will be used to add `get_current_pod().status.pod_ip` to all app's `ALLOWED_HOSTS` so that prometheus' service monitors would be able to access them. they cannot be configured with custom request headers

Add function to get current pod details

---

mtp_common/stack.py

because POD_NAME will not always be available

Fix current pod info loading

---

mtp_common/assets-src/stylesheets/_base.scss
setup.py

[MTP-1514](https://dsdmoj.atlassian.net/browse/MTP-1514)
Chrome appears to have a new default outline offset which has pushed the focus box outwards on links that are focused.
```css
// user agent style sheet
a:-webkit-any-link:focus {
outline-offset: 1px;
}
```
Example:
This does not happen in the latest Firefox or Safari
---
also:
- update kubernetes client to more closely match cloud platform
- use a single consistent version requirement for Django in all apps c.f. [MTP-1519](https://dsdmoj.atlassian.net/browse/MTP-1519)

Fix link focus outline on Chrome

---

build_tasks.py
mtp_common/__init__.py
mtp_common/nomis.py
package.json
tests/test_nomis.py

The new endpoint that HMPPS has chosen does not include `/elite2api/` in the URL. Because this is a breaking change and client apps must have updated settings, it seems safest to require new settings names entirely. The settings names are now more descriptive of what HMPPS is calling the associated components.
[MTP-1484](https://dsdmoj.atlassian.net/browse/MTP-1484)

Update NOMIS connector url handling to allow prison api path to be more flexible

---

docker-compose.yml

The reason for adding PYTHONUNBUFFERED is that setting this environment variable to a non-null value prevents python from caching STDOUT/STDERR, which can be confusing as with docker compose this cached output will be emitted on container restart, which can add complexity when trying establish when an error is thrown

Added PYTHONUNBUFFERED and normalised container naming conventions

---

mtp_common/test_utils/webdrivers.py

See https://stackoverflow.com/questions/59087200/google-chrome-failed-to-move-to-new-namespace

Added a fix to allow the functional tests to be run in docker, where chromeDriver cannot be sandboxed

---

Dockerfile-dev
build_tasks.py
mtp_common/__init__.py
mtp_common/build_tasks/tasks.py
package.json

Enabling shiny new pip dependency resolution (which we should start using at some point anyway) to work around an issue revolving around an erroneous implicit specification of the version of the python `Django` library now we specify it in this library alone and not in the money-to-prisoners services (in the name of reducing dependency complexity/duplication)

Enable python dependency resolution

---

Dockerfile-dev

This is necessary as a separate explicit command because we want to account for the case where we need to upgrade money-to-prisoners-common to the version specified in the requirements before running run.py build as run.py build may fail with import errors if it's being run against the old money-to-prisoners-common that is installed against the new code
This came about when upgrading django, but may happen with other major dependency upgrades too

MTP-1511 Account for case of running run.py build installed with old money-to-prisoners-common against new dependencies

---

build_tasks.py
mtp_common/build_tasks/tasks.py

Django's `call_command` was failing probably because it now takes arguments in a different way.
Also, pip now raises a warning about the 2020 resolver flag not having any effect.

Fix run.py test command

---

README.rst
run.py
setup.py

Simplify python dependency tree by removing [monitoring] extra from mtp-common. This allows all client apps to install the correct version of mtp-common on _first run_ (i.e. when none are installed) and without having to decide which extras it requires in the current environment.
---
Problem
-------
On first run (every run in CI and first run when developing locally), there is no mtp-common installed.
Currently it arbitrarily installed the _latest_ version.
This often means the build process then needs to re-install different versions of various packages.
This sometimes leads to import errors or incorrectly loaded libraries.
Locally, simply re-running the build script solves the issue, but in CI this is not possible
Solution
--------
Allow all client apps to easily install their base set …

Simpler python dependency tree

---

mtp_common/nomis.py

Some of the requests to NOMIS API are timing out despite the timeout being
15s (which is high).
The `retries` parameter for the following functions now defaults to `2`:
- `nomis.get_account_balances()`
- `nomis.get_transaction_history()`
- ~`nomis.get_photograph_data()`~
- `nomis.get_location()`
Hopefully this may help with some of the requests failing.
**NOTE**: There may be other places where HTTP requests are made and these
may still timeout but this is a first step and it should be relatively
safe.
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1768

nomis: Retry twice for nomis.get_* requests

---

.circleci/config.yml
.github/workflows/release.yml
README.rst
build_tasks.py
mtp_common/__init__.py
package.json
setup.py

… using twine (previously used an outdated mechanism to upload to PyPI).
There's a new Github action which is called when a release is made in Github.
It builds and packages mtp-common then uploads to PyPI.
[MTP-1539](https://dsdmoj.atlassian.net/browse/MTP-1539)

Allow releasing to PyPI using Github actions

---

mtp_common/build_tasks/executor.py

* Increased default verbosity was 1 (normal), increased to 2 (verbose).
* Show task name by default (`show_task_names`)
* Show task path/line number by default (`show_task_paths`, new)
Example:
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1797

Increased default verbosity of build_tasks

---

mtp_common/__init__.py
package.json
setup.py

This is to reduce dependencies duplication in the client applications
and avoid the risk of dependencies clashes.
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1537

11.0.1: Moved common dependencies here

---

docker-compose.yml

This is just a minor tweak so that when using docker-compose Cashbook FAQ
page shows some email address instead of awkard empty space.
**NOTE**: Related to [this other `cashbook` PR](https://github.com/ministryofjustice/money-to-prisoners-cashbook/pull/539).
Part of ticket: https://dsdmoj.atlassian.net/browse/MTP-1833

docker-compose: Added `FIU_EMAIL` env to cashbook

---

docker-compose.yml

Run `$ docker attach [container_name]` to attach to the running container.
This is useful to use debuggers like `pdb` in the running containers - without whatever is typed on the host doesn't seem to reach the containers.
See: https://stackoverflow.com/a/59717363

Ability to use pdb/attach to docker-compose containers

---

mtp_common/security/checks.py
tests/test_security_checks.py

…so that they can be displayed in a [form in noms-ops](https://github.com/ministryofjustice/money-to-prisoners-noms-ops/blob/9bef4c46667dd7dd1b63355682539a861fb0917d/mtp_noms_ops/apps/security/forms/check.py#L183) and [exported in human-readable form in api](https://github.com/ministryofjustice/money-to-prisoners-api/blob/fdf74298284804779e95294cf418ce97e5ea8666/mtp_api/apps/core/management/commands/dump_for_ap.py#L73) using the same standard labels.

Share security check rejection reason categories between all apps

---

docker-compose.yml

Configuring docker-compose to use local, editable, `mtp-common` has some
issues which are caused by the fact we're installing a new version of
`mtp-common` but then carry on within the same process which may still
point to old version/paths.
This may cause some assets to not be found.
I'm experimenting with the idea of splitting the `python_dependencies`
task from the `serve` task so that the serving of the application happens
after `mtp-common` is fully replaced (and in a new process).
See:
- https://github.com/ministryofjustice/money-to-prisoners-common/pull/420/files
- https://www.edureka.co/community/21344/how-do-i-execute-multiple-commands-using-docker-compose

docker-compose: Improvement to using mtp-common in editable modified

---

mtp_common/logging.py
tests/test_logging.py

For instance, the regular logging formatter will happily accept `logging.info('Model saved %s', model_instance)` because it uses string formatting to render the log message. The `ELKFormatter` now attaches all arguments passed to log messages so needs to be able to turn them into JSON.

Ensure ELK logging formatter can serialise any object passed to the log message

---

.github/workflows/release.yml
README.rst
run.py
setup.py

We're upgrading base images to Ubuntu 20.04 which comes with Python 3.8
so it makes sense to drop support for anything older and also run the
CI tests on Python 3.8.
PS: Also fixed `docker-compose build` command in README.
Ticket: https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=79&projectKey=MTP&modal=detail&selectedIssue=MTP-1841

Drop support for Python < 3.8

---

mtp_common/s3_bucket.py
mtp_common/tasks.py
setup.py
tests/test_s3_bucket.py
tests/test_stack.py
tests/utils.py

…which is shared amongst MTP apps in an environment. This utility
• automatically finds the appropriate bucket via a kubernetes secret
• can upload a file (setting tags and content type)
• can download a file directly into `bytes`
• can stream a download into an HTTP response
• generates urls for use in file downloads via new `emails` app (with random string to prevent enumeration and guessing of links)

Add wrapper utility for accessing S3 bucket

---

mtp_common/s3_bucket.py
tests/test_s3_bucket.py

… path such that bucket lifecycle applies and the downloadable files are logically name-spaced

Restrict download links from S3 to be only from under the `emails/*`

---

build_tasks.py
mtp_common/metrics/middleware.py
tests/test_metrics.py
tests/urls.py

By adding this _optional_ middleware, MTP apps can record the time HTTP requests take for collection by Prometheus (and therefore viewing in Grafana or alerting with Alertmanager)

Collect request duration metrics for Prometheus

---

mtp_common/auth/api_client.py
mtp_common/nomis.py

…for requests to mtp-api, hmpps-auth and prison-api

Increase default timeouts from 15 to 30s

---

mtp_common/auth/models.py
tests/test_models.py

This is needed to fix a problem where `opencensus-ext-django` tries to call the `get_username` method on `request.user` which can be `MojAnonymousUser` or `MojUser` in mtp client apps.

Add missing methods to faked MoJ user models to match Django models more closely

---

mtp_common/analytics.py
mtp_common/assets-src/mtp_common/components/analytics/index.js
mtp_common/assets-src/mtp_common/components/autocomplete-select/index.js
mtp_common/assets-src/mtp_common/components/before-unload/index.js
mtp_common/assets-src/mtp_common/components/print-analytics/index.js
mtp_common/templates/mtp_common/mtp_base.html
tests/test_context_processors.py

Overview of changes:
- updated `Analytics.py` to check if an app has the `GA4_MEASUREMENT_ID` setting set
- this will be used to calculate the `ga4_enabled` property
- updated `Analytics.js` 
- existing methods are mostly unchanged
- added `ga4SendEvent()` method added to send a custom even named `mtp_event` with the familiar category/action/label (retain this format helps the transition to GA4)
- added `ga4SendPageView()` method to send a `page_view` event - page views are tracked as usual but additional "page views" are sent for events across the apps
- update mtp-common JS code sending GA events/page views to also send these to GA4 (if GA4 available in the app)
- I could have done something within `Analytics.send()` to automagically send data to GA4 as well but I decided to keep it …

MTP-1937: Initial support for GA4

---

mtp_common/__init__.py
package.json

Should be a non-breaking release adding functionality (GA4 support) so bump the minor number is logical.

Bumped to 14.3.0 release

---

mtp_common/__init__.py
mtp_common/assets-src/mtp_common/components/analytics/index.js
package.json

Only `page_location` was provided before but path wouldn't show in GA4 interface.
The `Analytics.ga4SendPageView()` method now explicitly send location, path and title (these are read from the `.mtp-ga-data` data attributes if available).

MTP-1937: Send page path/location/title with GA4 page views

---

README.rst
mtp_common/__init__.py
mtp_common/auth/forms.py
mtp_common/user_admin/forms.py
package.json
setup.py

This is an internal package used to send form validation errors to GA. 
We've decided to to keep things simple and not update that package to work with the newer GA4's Measurement Protocol API.
As this is a breaking change `mtp-common`'s major version number has been bumped, new version is `15.0.0` [it is a breaking change as some of the mtp apps/forms are still using the `GARequestErrorReportingMixin` mixin until they're updated].

MTP-1937: Remove dependency on `django-form-error-reporting`

---

build_tasks.py
mtp_common/__init__.py
mtp_common/build_tasks/executor.py
mtp_common/templatetags/mtp_common.py
mtp_common/test_utils/__init__.py
package.json
setup.py
tests/test_auth_forms.py
tests/test_auth_views.py
tests/test_nomis.py
tests/test_notifications.py

We can merge these Django 3.2 changes into the `16.x` branch and release as `16.0.0` - this would allow us to test the applications more easily (and would make iterating changes there easier as tests could run in CI)
**NOTE**: Production applications would continue to use `mtp-common` `15.x` for the time being while we do some manual testing on the versions using Django 3.2.

Attempt to upgrade to Django 3.x

---

mtp_common/analytics.py
mtp_common/assets-src/mtp_common/components/analytics/index.js
mtp_common/assets-src/mtp_common/components/autocomplete-select/index.js
mtp_common/assets-src/mtp_common/components/before-unload/index.js
mtp_common/assets-src/mtp_common/components/print-analytics/index.js
mtp_common/templates/mtp_common/mtp_base.html
tests/test_analytics.py
tests/test_context_processors.py

- `Analytics.js`: removed deprecated methods/updated docs
- `AnalyticsPolicy`: removed legacy GA policy/updated tests
- base template: removed legacy GA tracking code
⚠️ NOTE: These are _potentially_ breaking changes and that's why this PR is on top of the 16.x branch rather than `main`.

MTP-1937: Remove legacy GA code

---

README.rst
mtp_common/security/checks.py
setup.py

• Remove 'known email' reason
• Add 'using a monitored keyword or email address'
• Remove 'associated FIU investigation' reason
• Add 'potential fraud'

MTP-1976: Update security check rejection categories

---

.github/dependabot.yml
mtp_common/notify/client.py
setup.py
tests/test_notify-simple.csv
tests/test_notify.py

Ref:
- [docs](https://docs.notifications.service.gov.uk/python.html#set-the-filename)
- [changes](https://github.com/alphagov/notifications-python-client/compare/8.2.0...9.0.0)

Update GOV.UK Notify client and allow specifying download file name

---

setup.py

[Attemp to release] mtp-common via the GH release/action is currently not working and throwing this exception:
```
Uploading distributions to https://upload.pypi.org/legacy/
ERROR    InvalidDistribution: Metadata is missing required fields: Name,
Version.
Make sure the distribution includes the files where those fields are
specified, and is using a supported Metadata-Version: 1.0, 1.1, 1.2,
Shell command `twine upload --non-interactive dist/*` exited with error code: 1
2.0, 2.1, 2.2, 2.3.
```
Not sure why this started to happen as we haven't touched the version of twine in awhile. However one of the suggestion in [this GH] is to upgrade to the latest version of twine which this commit is doing.
**NOTE**: I don't see anything particularly harmful in [the Twine changelog] even tho it's a …

Bump twine to latest version (6.1)

---

README.rst
mtp_common/__init__.py
setup.py

Also use newer versions of `django-moj-irat` and
`django-zendesk-tickets`: These versions only update package metadata necessary to install alongside
Django 5.2, nothing should change.

20.0.0: Bump to Django 5.2
