templates/mtp_base.html

This is part of multiple PRs across multiple repos to include GA in each app.

adds analytics JS code [updates #103597472]

---

assets/javascripts/modules/moj.show-hide.js
assets/scss/_mtp.scss
assets/scss/elements/_show-hide.scss

used to show/hide a set of target elements

adds a new module for creating show/hide or collapse/expand links

---

templates/auth/login.html

allows login template to handle non-field errors

---

templates/mtp_base.html

as on https://docs.google.com/document/d/1uAj9CbCS3MMUSVLaMLtqT4qrnYtjZa0wb_nGLxaB3cI/edit

update copy for feedback [updates #106947332]

---

assets/scss/elements/_summary-boxes.scss

Add space above the boxes now that the title is gone

---

assets/scss/elements/_content-header.scss

Remove prefix from Home link

---

bower.json

and update conflicting dependency

Use correct version of mojular

---

assets/javascripts/modules/feature-tour.js
assets/javascripts/modules/show-hide.js

Avoid using bind because IE8

---

assets/scss/elements/_upload.scss

So that the whole file path is visible
[Updates #109017446]

Make file upload controls 100% wide

---

assets/scss/_mtp.scss
assets/scss/elements/_content-header.scss
assets/scss/elements/_print-box.scss

- remove unneeded elements like application links
- add a print-box class to put specific content on printouts
[Updates #109440804]

Improve the layout of printed pages

---

templates/mtp_base.html

this is how it's provided by `django.template.context_processors.debug`

Renamed "debug" template context variable

---

package.json
templates/feedback/success.html

This page allows the user to return to what they were doing.

Feedback success page

---

Makefile
tasks.sh

All the makefile stuff that was in each application's repo is now here and what's left in the applications is a tiny script that calls the makefile here.

Enable all applications to build or run from a script

---

Makefile
tasks.sh

- collect images everywhere
- export NODE_BIN so it can be used in subshell
- prepare virtual env before running tests

Add some fixes for the scripts to work

---

assets/javascripts/modules/dialog.js

Will provide a better pageflow behaviour visualisation

Track dialog open and close as GA virtual pageviews

---

Makefile
assets/javascripts/modules/analytics.js
assets/javascripts/modules/dialog.js
assets/javascripts/modules/unload.js

- calling the function analytics.send()
- or adding the data-analytics attribute to a clickable element

Add a module to make GA pageview or event calls

---

Makefile

- don't monitor all files in common (like .git)
- light build target for live-reload work
- couple of small fixes

Make less work in makefile

---

Makefile

otherwise, the latest compiled assets will not be available to S3 uploader / nginx

Collect static files as the last step in build process

---

templates/mtp_base_public.html

As per https://notableapp.com/posts/1156106

Use the right feedback text for public pages

---

templates/auth/password_change.html
templates/auth/password_change_done.html

Includes password change form and confirmation page.

Add common templates for an authed user to change their password

---

templates/forms/generic.html

Use li elements inside of ol rather than br.

Make error display formatting follow standards

---

package.json
templates/auth/login.html
templates/forms/generic.html

NB: MTP client applications need converting before they can use this version of mtp-common

Replace ministryofjustice/django-utils dependency with ministryofjustice/money-to-prisoners-utils

---

assets/javascripts/modules/help-popup.js
assets/scss/elements/_help-popup.scss

- avoid h3 to avoid breaking heading hierarchy
- use fewer style rules

Simplify markup and CSS of help-boxes

---

templates/mtp_base.html

See https://support.google.com/analytics/answer/2558867?hl=en

Trigger GA's enhanced link tracking

---

assets/scss/elements/_help-popup.scss

Show list markers in help popups

---

assets/javascripts/modules/track-printing.js
templates/mtp_base.html

Part of https://www.pivotaltracker.com/story/show/108758158

Print tracking

---

mtp_common/assets/scss/_base.scss
mtp_common/templates/mtp_common/mtp_base.html
mtp_common/templates/mtp_common/mtp_base_public.html

https://www.pivotaltracker.com/story/show/117696495

Replace alpha banner with dev/test banner on dev and test environments

---

mtp_common/Makefile

1. Remove pre_build as the copying will be replaced with symlinking
2. Use -zsh and not make
3. Be less verbose

Improve the makefile:

---

mtp_common/assets/javascripts/modules/upload.js
mtp_common/assets/scss/_base.scss
mtp_common/assets/scss/elements/_upload.scss

1. removed lodash, use jquery's proxy instead
2. removed spinner -- not needed (didn't show on IE8 anyway)
3. Make a nicer user experience and look better (designs at https://notableapp.com/sets/81879)
4. Work when no js
Part of https://www.pivotaltracker.com/story/show/119005035

New upload control

---

mtp_common/assets/scss/elements/_summary-boxes.scss

- make boxes flow as intended, esp on IE8
- make variant names generalised, not just for cashbook
- allow for smaller titles

Improve summary boxes:

---

mtp_common/email.py
mtp_common/templates/mtp_common/email_base.html

Also add a base template for HTML emails.

Create util function for easier email sending

---

mtp_common/assets/scss/_base.scss
mtp_common/templates/mtp_common/mtp_base.html

- Only show menu when there are items
- Fix menu style so it doesn't show list item bullets

Fix responsive menu

---

mtp_common/Makefile

And rename the static_assets rule to indicate it's not a dependency but a command

Don't collect all assets when running tests

---

mtp_common/Makefile
mtp_common/management/commands/takescreenshots.py
mtp_common/screenshots.py
mtp_common/test_utils/functional_tests.py
setup.py

Adds a 'takescreenshots' command which will scan for test_screenshots.py
files and run the testcases inside. These should be based on the included
LiveServerTestCase subclass which uses phantomjs to generate screenshots of
the pages navigated to by the test methods.
The LiveServerThread used by the testcase can be replaced with a subclass
which allows for mocking of api responses etc

Add screenshot generation to build process

---

mtp_common/assets/javascripts/modules/collapsing-table.js
mtp_common/assets/scss/elements/_collapsing-table.scss

Changed the tag from a span to an anchor tag.

Include collapsible table toggle in tab focus

---

mtp_common/templates/mtp_common/user_admin/base.html
mtp_common/templates/mtp_common/user_admin/delete.html
mtp_common/templates/mtp_common/user_admin/deleted.html
mtp_common/templates/mtp_common/user_admin/list.html
mtp_common/templates/mtp_common/user_admin/saved.html
mtp_common/templates/mtp_common/user_admin/update.html

and replace "dashboard" link to generic "/" which won't work in all client apps

Factor out base user account management template

---

mtp_common/__init__.py
mtp_common/auth/api_client.py

otherwise nginx times out and then no proper error page can be displayed

Make authentication-related api calls time out

---

mtp_common/assets/javascripts/modules/proposition-header.js
mtp_common/assets/scss/_base.scss
mtp_common/assets/scss/_mtp.scss
mtp_common/assets/scss/_utilities.scss
mtp_common/assets/scss/elements/_account-management.scss
mtp_common/assets/scss/elements/_proposition.scss
mtp_common/templates/mtp_common/mtp_base.html

client apps will need to include a complete `proposition_menu` block with log-out links etc and add `require('proposition-header').PropositionHeader.init()` to the main javascript

Navigation changes

---

mtp_common/templates/mtp_common/feedback/submit_feedback.html
mtp_common/templates/mtp_common/feedback/success.html

currently, the content is shared across all MTP apps

Add feedback view templates to use new style breadcrumbs

---

mtp_common/uwsgidecorators.py

For some reason this version is not in the latest releases of
uwsgi.

Add version of uwsgidecorators.py with python3 compat fixes

---

mtp_common/assets/scss/_mtp.scss
mtp_common/assets/scss/elements/_language-switch.scss
mtp_common/templates/mtp_common/auth/login.html
mtp_common/templates/mtp_common/auth/password_change.html
mtp_common/templates/mtp_common/auth/password_change_done.html
mtp_common/templates/mtp_common/feedback/submit_feedback.html
mtp_common/templates/mtp_common/forms/generic.html
mtp_common/templates/mtp_common/language-switch.html
mtp_common/templates/mtp_common/user_admin/delete.html
mtp_common/templates/mtp_common/user_admin/list.html
mtp_common/templates/mtp_common/user_admin/update.html
mtp_common/templatetags/mtp_common.py

• optionally turned on via settings
• template tag for including in client apps
• included in shared non-final pages (you can't reload a final page so you'd be redirected anyway)

Add language switching

---

mtp_common/assets-src/javascripts/modules/placeholder-polyfill.js
mtp_common/assets-src/stylesheets/_mtp.scss
mtp_common/assets-src/stylesheets/elements/_placeholder-polyfill.scss

Add a polyfill for placeholder text in input elements

---

mtp_common/assets-src/stylesheets/elements/_account-management.scss
mtp_common/templates/mtp_common/user_admin/list.html
mtp_common/user_admin/urls.py
mtp_common/user_admin/views.py

depends on [api#310](https://github.com/ministryofjustice/money-to-prisoners-api/pull/310)

User admin lockout

---

mtp_common/assets-src/javascripts/modules/polyfills.js

Polyfill sourced from:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill

Add polyfill for 'bind' function method on IE8

---

mtp_common/assets-src/stylesheets/_base.scss
mtp_common/assets-src/stylesheets/elements/_language-switch.scss

And reduce spacing with breadcrumbs.

Reposition language switch to just above header

---

mtp_common/auth/models.py
setup.py

Change certain methods in User subclasses to properties to match
django 1.10

Update django version to 1.10

---

mtp_common/nomis.py
tests/test_nomis.py

As we are in fact expected to generate a new bearer token for each
request, no point in having a class.

Convert NOMIS functionality to module functions

---

mtp_common/auth/models.py
mtp_common/locale/cy/LC_MESSAGES/django.po
mtp_common/locale/en_GB/LC_MESSAGES/django.po
mtp_common/templates/mtp_common/feedback/submit_feedback.html
mtp_common/templates/mtp_common/user_admin/incompatible-admin.html
mtp_common/templates/mtp_common/user_admin/incompatible-user.html
mtp_common/templates/mtp_common/user_admin/update.html
mtp_common/templates/mtp_common/user_admin/user-description.html
mtp_common/user_admin/forms.py
mtp_common/user_admin/views.py
tests/test_user_admin_views.py

depends on [api#349](https://github.com/ministryofjustice/money-to-prisoners-api/pull/349)

Update user management forms to be role-based

---

mtp_common/templates/mtp_common/feedback/submit_feedback.html
mtp_common/templates/mtp_common/user_admin/incompatible-admin.html
mtp_common/templates/mtp_common/user_admin/incompatible-user.html

and allow email address to be set too

Fix contact form pre-filling

---

mtp_common/templates/mtp_common/sentry-js.html
setup.py

version 3.8.1 JS client results in IE8 error

Upgrade raven/sentry

---

mtp_common/nomis.py

New transaction code is specifically for money through the
digital service.

Change transaction code from MRPR to MTDS

---

mtp_common/templates/mtp_common/feedback/submit_feedback.html
mtp_common/templates/mtp_common/feedback/success.html
mtp_common/views.py

Add common "get help" class-based views

---

mtp_common/nomis.py

Allow the client to choose the NOMIS transaction type

---

mtp_common/nomis.py

Just make the naming less credit-specific.

Generalise function for creating NOMIS transactions

---

mtp_common/assets-src/javascripts/modules/tabbed-panel.js
mtp_common/assets-src/stylesheets/elements/_tabbed-panel.scss
mtp_common/templates/mtp_common/includes/panel-tab.html
mtp_common/templates/mtp_common/includes/tabbed-panel.html
mtp_common/templatetags/mtp_common.py

extracted from noms-ops security forms

Add tabbed panel template tags

---

mtp_common/stack.py
setup.py
tests/test_stack.py

Update check for EC2 instance being first (ordering by instance id) in ASG and "in-service"

---

mtp_common/tasks.py
setup.py
tests/test_spooling.py

so that stats are categorised in Mailgun

Add tagging to emails sent out via Anymail

---

.travis.yml
run.py
setup.py
tests/test_spooling.py

… because it resolves requirements better

Use pip to install dependencies in Travis tests

---

mtp_common/templates/mtp_common/user_admin/update.html
tests/test_user_admin_views.py

This removes cross-application user management

Remove support for roles managing other roles

---

mtp_common/analytics.py
mtp_common/auth/views.py

Also apply it to the reset password page.

Add GA genericisation function to common

---

mtp_common/tasks.py

for use in other places that send emails differently

Factor out default email parameters

---

mtp_common/auth/forms.py

Add note to login page about username==Quantum ID

---

mtp_common/templatetags/mtp_common.py
mtp_common/utils.py
tests/test_templatetags.py

…falls back to simply using upper case

Add template tag for spacing out postcodes

---

mtp_common/assets-src/stylesheets/elements/_ie-support-banner.scss
mtp_common/templates/mtp_common/cp_migration/maintenance.html
mtp_common/templates/mtp_common/cp_migration/we-have-moved.html

So that they look prettier.
**Maintenance**
**We have moved - non-IE8 version**
**We have moved - IE8 version**

Update cloud platform migration pages

---

mtp_common/build_tasks/executor.py

pip 19.3 moved the main function to the `_internal.main` module so we now need to import the right module depending on the pip version.

Add support for pip 19.3

---

mtp_common/nomis.py
tests/test_nomis.py

Before rolling that out to all prisons.

Limit NOMIS Elite2 write ops to one prison only

---

.github/CODEOWNERS
README.rst
mtp_common/auth/basic.py
mtp_common/build_tasks/executor.py
mtp_common/metrics/app.py
mtp_common/metrics/metrics.py
mtp_common/metrics/views.py
setup.py
tests/test_basic_auth.py
tests/test_metrics.py
tests/urls.py

this would not be a major version change as it's compatible with apps that haven't been updated

Remove template deploy artefacts

---

mtp_common/__init__.py
mtp_common/auth/backends.py
mtp_common/auth/views.py
mtp_common/build_tasks/executor.py
package.json
setup.py

Finally got to the bottom of devilishly devious testing issue arising from mtp_common.auth.backends.MojBackend.authenticate changing interface invisibly due to being mocked

MTP-1511 Upgrade mtp_common to django==2.2.*

---

README.rst
mtp_common/__init__.py
mtp_common/auth/views.py
mtp_common/feedback/views.py
package.json
setup.py

* Updated previously missed invocations of is_safe_url to Django>=2.2
* incremented versions of bespoke dependencies 
* added to documentation
I can break the version increment out into it's own commit if you prefer

MTP-1511 money-to-prisoners-common 10.0.1 patch release

---

mtp_common/tasks.py
tests/test_spooling.py

Previously, client apps that sent emails all required `django-anymail` internally. Now that the dependency is here, no branching is needed in email-sending tasks.

Remove fallback now that django-anymail is always available

---

.gitignore
mtp_common/__init__.py
mtp_common/assets-src/mtp_common/components/account-management/_index.scss
mtp_common/templates/mtp_common/user_admin/sign-up.html
mtp_common/user_admin/forms.py
package.json

Jira: https://dsdmoj.atlassian.net/browse/MTP-1805
Linked PRs:
* Cashbook: https://github.com/ministryofjustice/money-to-prisoners-cashbook/pull/542
* API: https://github.com/ministryofjustice/money-to-prisoners-api/pull/642

MTP-1805 Request an Account

---

.gitignore
build_tasks.py
mtp_common/assets-src/mtp_common/components/accordion/index.js
mtp_common/assets-src/mtp_common/components/card/_index.scss
mtp_common/assets-src/mtp_common/components/link/_index.scss
mtp_common/assets-src/mtp_common/components/print-trigger/index.js
mtp_common/assets-src/mtp_common/components/table/_extension.scss
mtp_common/build_tasks/app.py
mtp_common/build_tasks/tasks.py
mtp_common/templates/mtp_common/auth/login.html
mtp_common/templates/mtp_common/build_tasks/eslintrc.json
mtp_common/templates/mtp_common/build_tasks/package.json
mtp_common/templates/mtp_common/components/card-group.html
mtp_common/templates/mtp_common/feedback/submit_feedback.html
mtp_common/templates/mtp_common/forms/generic.html
mtp_common/templates/mtp_common/sentry-js.html
mtp_common/templates/mtp_common/user_admin/accept-request.html
mtp_common/templates/mtp_common/user_admin/delete.html
mtp_common/templates/mtp_common/user_admin/sign-up-confirm-changes.html
mtp_common/templates/mtp_common/user_admin/sign-up.html
mtp_common/templates/mtp_common/user_admin/undelete.html
mtp_common/templates/mtp_common/user_admin/update.html
package.json
tests/test_code_style.py

mostly just updates of dependencies, but includes some display fixes

Bundle of fixes and updates related to GOV.UK Design System update of MTP apps

---

mtp_common/logging.py
mtp_common/spooling.py
mtp_common/user_admin/forms.py
mtp_common/user_admin/views.py

Jira: https://dsdmoj.atlassian.net/browse/MTP-1863
* Ensure any logger args are included in ELK payload
* Removed identifiers from exception/logger messages and pass seperately to help sentry deduplicate issues

MTP-1863 Remove remaining identifiers from exceptions and attach to sentry metadata

---

mtp_common/assets-src/mtp_common/_index.scss
mtp_common/assets-src/mtp_common/components/breadcrumb-bar/_index.scss
mtp_common/assets-src/mtp_common/components/masthead/_index.scss
mtp_common/assets-src/mtp_common/components/panel/_index.scss
mtp_common/templates/mtp_common/build_tasks/package.json
mtp_common/templates/mtp_common/components/breadcrumb-bar.html

…which improves the readability of linked text

Update to latest GOV.UK Design System

---

mtp_common/assets-src/mtp_common/components/account-management/_index.scss
mtp_common/templates/mtp_common/user_admin/list.html
mtp_common/templates/mtp_common/user_admin/update.html
mtp_common/user_admin/forms.py
mtp_common/user_admin/urls.py
mtp_common/user_admin/views.py
tests/test_user_admin_views.py

This will allow filtering/searching list of users and make it easier to enable/disable a user once found.
Depends on [mtp-api#751](https://github.com/ministryofjustice/money-to-prisoners-api/pull/751)

Improve user management

---

README.rst

@ushkarev from the GH docs it seems merging a PR would merge it into it's "base branch" (which makes sense) - I'm giving it a try and see if this would merge into the `16.x` branch as expected.

Test commit - Updated README
